apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-com
  template:
    metadata:
      labels:
        app: e-com
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cache
            topologyKey: kubernetes.io/hostname
      containers:
      - name: web-app
        image: vinayjadhav/app:v1.0.0
        ports:
        - containerPort: 8080
        